baseURL = "https://www.alvarezquinterobanda.com"
languageCode = "es"

Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
  text_color = ""
  favicon = "/images/site-logo.jpeg"
  site_logo = "/images/site-logo.jpeg"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/bandaalvarezqui?lang=es"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/bandaalvarezquintero/"

[[params.ananke_socials]]
name = "facebook"
url = "https://es-la.facebook.com/bandaalvarezquintero.utrera"
